import Head from 'next/head'
import Link from "next/link"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="container mx-auto">
        <Link
          href="/"
        >
          <a>Home</a>
        </Link>
      </nav>

      <main className="container mx-auto">
        <p>Logo</p>
        <h1 className="text-5xl font-bold">A great keyboard shortcut experience for your users in no time</h1>
        <p className="text-xl">A one minute installation that covers all your user needs when it comes to shortcuts and search.</p>
      </main>
    </div>
  )
}
