name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 14"
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        #- name: "Setup npm"
        #  run: |
        #    npm set @arnklint:registry=https://registry.npmjs.org/arnklint
        #    npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH }}"

        #- name: "Version and publish"
        #  env:
        #    GH_TOKEN: ${{ secrets.NPM_PUBLISH }}

        #GH_TOKEN: ${{ secrets.NPM_PUBLISH }}
        #git config user.name "${{ github.actor }}"
        #git config user.email "${{ github.actor}}@users.noreply.github.com"

        #- run: npm install
        #- run: npm publish
        #git config user.name github-actions
        #git config user.email github-actions@github.com

      run: |
        npx lerna version --conventional-commits --conventional-graduate --yes
        npx lerna publish from-git --yes
