name: Publish Beta
on:
  push:
    branches:
      - development

jobs:
  publish_beta:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 14"
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        npx lerna publish from-git --yes
