name: Release

on:
  push:
    branches:
      - development
      - main

jobs:
  publish-gpr:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # pulls all tags (needed for lerna to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # see https://stackoverflow.com/a/60184319/9285308

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Ensure access
        run: npm whoami --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          

      - name: Bootstrap lerna
        run: npx lerna bootstrap

      - name: Bootstrap lerna
        run: npx lerna run build

      - name: Bump versions and publish packages
        run: |
          npm set @arnklint:registry=https://registry.npmjs.org/arnklint
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH }}"
          if [ ${{ github.ref }} = refs/heads/development ]; then
            npm run beta:version:ci
          else
            npm run version:ci
          fi
          npm run publish:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
